### ISSUE TITLE
design of comment box

### ISSUE THREAD

**Issue by alexandravo** [cgoldammer/punorama#5]
- overall these comment boxes should be much smaller than the pun box
- can the text field be bigger relative to the button panel + button should say Comment, not Add to Punorama in the comment box. Alternatively, instead of having the "comment" and "cancel" buttons, you could save space by replacing "comment" by placeholder text "Write a comment.." (purely inspired by FB here lol) and "close" button by "x" box on the right of the textbox

**Comment by cgoldammer** [comment]
I've done parts of this.
