### ISSUE TITLE
design of adding puns

### ISSUE THREAD

**Issue by alexandravo** [cgoldammer/punorama#9]
- for adding puns, similarly to commenting box, make text box longer
- similarly again for adding puns, maybe replace buttons by "Write a pun..." placeholder text (although maybe having a button that makes submitting a new pun more salient is good too) and "Cancel" button by red "x" box.
- for existing puns, make button panel smaller. maybe consider replacing edit and delete button by pencil and trash can glyphicons

**Comment by cgoldammer** [comment]
This is done!
